// audio module — wrap oggenc2.exe for FNV voice/sound. Commands: wav-to-ogg, info, lip
// .lip generation is GECK-only (FonixData) — not possible from a CLI.
const fs = require('fs');
const { execFileSync } = require('child_process');

function oggenc(ctx) {
    const exe = ctx.findTool(['oggenc2.exe', 'oggenc.exe']);
    if (!exe) ctx.fail('oggenc2.exe not found (searched the FNV game folder and PATH). Install oggenc2 (vorbis-tools).');
    return exe;
}

function oggInfo(file) {
    const buf = fs.readFileSync(file);
    const i = buf.indexOf(Buffer.from('\x01vorbis', 'latin1'));
    if (i < 0) return null;
    return {
        channels: buf[i + 11],
        sampleRate: buf.readUInt32LE(i + 12),
        nominalBitrate: buf.readInt32LE(i + 20),
    };
}
function wavInfo(file) {
    const buf = fs.readFileSync(file);
    if (buf.toString('latin1', 0, 4) !== 'RIFF') return null;
    const fmt = buf.indexOf(Buffer.from('fmt ', 'latin1'));
    if (fmt < 0) return null;
    return {
        channels: buf.readUInt16LE(fmt + 10),
        sampleRate: buf.readUInt32LE(fmt + 12),
        bits: buf.readUInt16LE(fmt + 22),
    };
}

exports.run = async (command, ctx) => {
    const { positionals, flags, emit, fail, dryRun } = ctx;

    switch (command) {
        case 'wav-to-ogg': {
            const [input, output] = positionals;
            if (!input || !output) return fail('usage: audio wav-to-ogg <in.wav> <out.ogg> [--quality N] [--rate 24000] [--stereo] [--dry-run]');
            const exe = oggenc(ctx);
            const rate = String(flags.rate ?? 24000);   // FNV voice = 24 kHz
            const q = String(flags.quality ?? 1);        // ~64 kbps avg VBR
            const args = [];
            if (!flags.stereo) args.push('--downmix');   // mono by default (voice)
            args.push('--resample', rate, '-q', q, '-o', output, input);
            if (dryRun) return emit({ action: 'wav-to-ogg', input, output, rate, quality: q, mono: !flags.stereo, dryRun: true, wouldRun: 'oggenc2 ' + args.join(' ') });
            execFileSync(exe, args, { encoding: 'utf8' });
            return emit({ action: 'wav-to-ogg', input, output, bytes: fs.statSync(output).size, ...oggInfo(output) });
        }

        case 'info': {
            const file = positionals[0];
            if (!file) return fail('usage: audio info <file.ogg|.wav>');
            const ext = file.toLowerCase().slice(-4);
            const info = ext === '.ogg' ? oggInfo(file) : wavInfo(file);
            if (!info) return fail('could not read audio header (supported: .ogg, .wav)');
            return emit({ action: 'info', file, format: ext.slice(1), ...info });
        }

        case 'lip':
            return fail('FNV .lip files are generated by the GECK (assign WAV to a dialogue response → FromWav → GenerateLipFile, with FonixData.cdf) — not by oggenc/CLI. See the fnv-audio skill.');

        default:
            return fail(`audio: unknown command '${command}'. Commands: wav-to-ogg, info, lip`);
    }
};
