"""MCP tools for FNV voice/sound audio, backed by the toolbox's AutoMod `audio`
module (oggenc2) via the AutoMod bridge.

FNV voice = .ogg + separate .lip (NOT Skyrim's bundled .fuz/.xwm) — so the upstream
FUZ split/extract tools are dropped. Instead:
- `mo2_audio_info`    — metadata for .ogg/.wav.
- `mo2_convert_audio` — WAV -> FNV-spec OGG (24 kHz mono by default), into the output mod.

.lip lip-sync files are generated by the GECK (FonixData), not from a CLI — see the
toolbox's fnv-audio skill.
"""

import json
import os

from PyQt6.QtCore import qInfo, qWarning

import mobase

from .config import PLUGIN_NAME
from .automod_bridge import run_automod


def register_audio_tools(registry, organizer: mobase.IOrganizer) -> None:

    registry.register(
        name="mo2_audio_info",
        description=(
            "Return metadata for an FNV voice/sound file (.ogg or .wav): format, "
            "channels, sample rate, and bitrate/bit depth. Takes a VFS or absolute path."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "audio_path": {"type": "string", "description": "VFS or absolute path to a .ogg or .wav file."},
            },
            "required": ["audio_path"],
        },
        handler=lambda args: _handle_audio_info(organizer, args),
    )

    registry.register(
        name="mo2_convert_audio",
        description=(
            "Convert a WAV to FNV voice-spec OGG (default 24 kHz mono, ~64 kbps VBR) "
            "via oggenc2, written into the output mod. Pass stereo=true for non-voice "
            "sound. (.lip lip-sync is GECK-only — see the fnv-audio skill.)"
        ),
        input_schema={
            "type": "object",
            "properties": {
                "wav_path": {"type": "string", "description": "VFS or absolute path to the source .wav."},
                "output_name": {"type": "string", "description": "Relative .ogg path inside the output mod (default: same name as the WAV, e.g. 'sound/voice/.../line.ogg')."},
                "stereo": {"type": "boolean", "description": "Keep stereo (default false = downmix to mono, correct for voice).", "default": False},
                "rate": {"type": "integer", "description": "Sample rate in Hz (default 24000, FNV voice).", "default": 24000},
                "quality": {"type": "integer", "description": "oggenc VBR quality (default 1, ~64 kbps).", "default": 1},
            },
            "required": ["wav_path"],
        },
        handler=lambda args: _handle_convert_audio(organizer, args),
    )


def _resolve(organizer, path: str, kind: str):
    if not path:
        return None, f"{kind}_path is required."
    if os.path.isabs(path) and os.path.isfile(path):
        return path, None
    disk = organizer.resolvePath(path.replace("/", "\\"))
    if not disk or not os.path.isfile(disk):
        return None, f"{kind} not found in VFS: {path}"
    return disk, None


def _handle_audio_info(organizer, args: dict) -> str:
    disk, err = _resolve(organizer, args.get("audio_path", ""), "audio")
    if err:
        return json.dumps({"error": err})
    res = run_automod(organizer, "audio", "info", [disk], timeout=30)
    if not res.get("ok"):
        return json.dumps({"error": res.get("error", "audio info failed"), "detail": res.get("stderr")})
    return json.dumps({
        "success": True,
        "audio": disk.replace("\\", "/"),
        "result": {k: v for k, v in res.items() if k not in ("ok", "action", "file")},
    }, indent=2)


def _handle_convert_audio(organizer, args: dict) -> str:
    disk_in, err = _resolve(organizer, args.get("wav_path", ""), "wav")
    if err:
        return json.dumps({"error": err})
    if not disk_in.lower().endswith(".wav"):
        return json.dumps({"error": f"Not a .wav file: {disk_in}"})

    output_mod = organizer.pluginSetting(PLUGIN_NAME, "output-mod")
    if not output_mod:
        return json.dumps({"error": "No output mod configured in plugin settings."})
    output_mod_dir = os.path.join(organizer.modsPath(), output_mod)

    rel_out = args.get("output_name") or (os.path.splitext(os.path.basename(disk_in))[0] + ".ogg")
    rel_out = rel_out.replace("/", os.sep).lstrip("/\\")
    if ".." in rel_out:
        return json.dumps({"error": "output_name must not contain '..'."})
    if not rel_out.lower().endswith(".ogg"):
        rel_out += ".ogg"
    final_path = os.path.join(output_mod_dir, rel_out)
    if not os.path.normpath(final_path).startswith(os.path.normpath(output_mod_dir)):
        return json.dumps({"error": "Output path escapes the output mod directory."})
    if os.path.exists(final_path):
        return json.dumps({"error": f"Output file already exists: {rel_out}. Delete first.", "existing_path": final_path})

    os.makedirs(os.path.dirname(final_path), exist_ok=True)

    cli_args = [disk_in, final_path, "--rate", str(int(args.get("rate", 24000))), "--quality", str(int(args.get("quality", 1)))]
    if args.get("stereo"):
        cli_args.append("--stereo")

    res = run_automod(organizer, "audio", "wav-to-ogg", cli_args, timeout=120)
    if not res.get("ok"):
        # clean up any zero-byte partial
        if os.path.exists(final_path) and os.path.getsize(final_path) == 0:
            try:
                os.remove(final_path)
            except OSError:
                pass
        return json.dumps({"error": res.get("error", "audio wav-to-ogg failed"), "detail": res.get("stderr")})

    if not os.path.isfile(final_path):
        return json.dumps({"error": "AutoMod reported success but no OGG was produced.", "automod_result": res})

    size = os.path.getsize(final_path)
    qInfo(f"{PLUGIN_NAME}: converted '{os.path.basename(disk_in)}' -> {rel_out} ({size} bytes)")
    try:
        organizer.refresh(save_changes=True)
    except Exception as exc:
        qWarning(f"{PLUGIN_NAME}: organizer.refresh() failed after audio convert: {exc}")

    return json.dumps({
        "success": True,
        "input": disk_in.replace("\\", "/"),
        "output_path": final_path.replace("\\", "/"),
        "size_bytes": size,
        "channels": res.get("channels"),
        "sample_rate": res.get("sampleRate"),
        "next_step": (
            f"Converted OGG is visible to mo2_list_files via MO2's VFS (as long as "
            f"'{output_mod}' is enabled in MO2's left pane)."
        ),
    }, indent=2)
